### ISSUE TITLE
Method "add" can't work well with arrays

### ISSUE THREAD

**Issue by sukazavr** [planttheidea/unchanged#10]
Hello! I've found smth :-)

Mb it's not a bug, let me just show you:

> ![image](https://user-images.githubusercontent.com/2406951/35720730-fcf0c6b4-07ff-11e8-95d9-e708d18f11b9.png)

What do u think?

**Comment by planttheidea** [comment]
No, this is definitely a bug ... the results of the first example (`['d', 'f']`) should mimic that of the second example (`'d.f'`). I have a fix for this, should be out shortly. Thanks!
