### ISSUE TITLE
array.slice ?

### ISSUE THREAD

**Issue by crazy4groovy** [planttheidea/unchanged#12]
Cool lib!

Is it better/faster [here](https://github.com/planttheidea/unchanged/blob/master/src/utils.js#L67) to clone with `array.slice()` instead of `.map(...)`?

**Comment by planttheidea** [comment]
You know, when I was writing this code I tested both and `map` was slightly faster, but I was using a beta verison of node (`9.2.0` or something). I've switched over to using LTS for a more real-life analysis, and not only is `slice` less code, it is actually quite a bit faster!

Good catch, I'll release an update posthaste.

**Comment by planttheidea** [comment]
Released as `1.0.6` from #13
