### ISSUE TITLE
Expose getOr?

### ISSUE THREAD

**Issue by jetpacmonkey** [planttheidea/unchanged#17]
I see `onMatchAtPath` already supports a `noMatchValue`, so I wouldn't imagine it would be especially difficult to add functionality equivalent to lodash/fp's `getOr`, allowing the caller to provide a fallback value, with the signature `getOr(fallback, path, object)`.

I could submit a PR, I just wanted to see if there was interest first.

**Comment by planttheidea** [comment]
Definitely! I was actually unaware of lodash's `getOr`, and you're right this should be pretty easy to add. If you want to send a PR my way, I'd appreciate it!

**Comment by jetpacmonkey** [comment]
It's not in regular lodash as it's own function, because it's just the 3rd parameter to `_.get`, but it's added in lodash/fp as a new method to support that optional param. I'll throw up a PR later today, thanks for the great library!

**Comment by planttheidea** [comment]
This is released as part of `1.2.0`. Thanks for the PR!
